# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yEvL8GQEMfZYPnHT37y1Zek6i6BU9bVF
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['xy_data.csv']))
print(df.head())

import pandas as pd
import numpy as np
from scipy.optimize import least_squares

# 1. Load Data
df = pd.read_csv('xy_data.csv')
X_data = df['x'].values
Y_data = df['y'].values
N = len(df)

# 2. Estimate t Values (Uniform sampling)
t_min = 6.0
t_max = 60.0
t_values = np.linspace(t_min, t_max, N)

def parametric_curve(t, theta, M, X):
    #Calculates (x, y) coordinates for a given t and parameters
    t_abs = np.abs(t)
    e_term = np.exp(M * t_abs) * np.sin(0.3 * t)

    x = t * np.cos(theta) - e_term * np.sin(theta) + X
    y = 42 + t * np.sin(theta) + e_term * np.cos(theta)
    return x, y

def residuals(params, t, x_data, y_data):
    #Calculates the residuals (errors) for the least squares optimization
    theta, M, X = params
    x_pred, y_pred = parametric_curve(t, theta, M, X)

    # Concatenate the x and y errors into a single 1D array
    return np.concatenate([(x_pred - x_data), (y_pred - y_data)])

# Convert theta bounds from degrees to radians
theta_rad_max = 50 * np.pi / 180.0

# Initial Guess (P0 = [theta_rad, M, X])
theta_0 = 25 * np.pi / 180.0  # Middle of the range
M_0 = 0.0                    # Middle of the range
X_0 = 50.0                   # Middle of the range
P_0 = np.array([theta_0, M_0, X_0])

# Bounds: ([theta_min, M_min, X_min], [theta_max, M_max, X_max])
bounds = ([0.0, -0.05, 0.0], [theta_rad_max, 0.05, 100.0])

# Perform the least-squares optimization
result = least_squares(
    residuals,
    P_0,
    args=(t_values, X_data, Y_data),
    bounds=bounds
)

# Extract optimal parameters
theta_opt, M_opt, X_opt = result.x